### ISSUE TITLE
Refactor Article view stuff

### ISSUE THREAD

**Issue by chrisjlebron** [chrisjlebron/rgb-search#3]
### TODO's
- [ ] clean up route handling
  - [x] all views should be handled through Router
  - [ ] articles view should be sub route of color wheel search
- [ ] clean up data handling
  - [ ] add Redux to handle full app state in a way that is smarter
- [ ] rethink components to make more "stateless/pure"
### Nice to haves
- [ ] expand article view to article detail
  - [ ] click handler for `ListItems` when `state.view === articles` will be to expand box and reveal full article
- [ ] add CSS for articles
  - ~~color as transparent overlay over image~~
  - [ ] layouts: Title, Blurb, Image => Title, Image, Full_Text
  - [ ] animation for expansion/collapse
